### PR TITLE
Log running jobs and failed services summary

### PR DESCRIPTION
**Pull request by scottwakeling**
Start to explore the systemd1 interface by logging a summary of running jobs and failed services.

e.g.

Failed Units:
- user@65534.service (loaded failed failed) result: timeout since: 2015-02-10 17:02:35

### CODE REVIEW

**Comment by spanezz** [comment]
On Sun, Feb 15, 2015 at 03:47:23PM -0800, Scott Wakeling wrote:

> Start to explore the systemd1 interface by logging a summary of running jobs
> and failed services.

Hi, I like that idea, and I've also merged the Debian packaging.

It looks like my attention has already shifted to other works. I've
added you as a contributor in the repository so you can push directly to
it.

Would you like to take it over as the lead developer?

Enrico

## 

GPG key: 4096R/E7AD5568 2009-05-08 Enrico Zini enrico@enricozini.org

**Comment by scottwakeling** [comment]
> ...
> Would you like to take it over as the lead developer?

Thanks, I'll take it over. There's some more I'd like to add..

## 

4096R/B4CCF23A 2014-11-20 Scott James Wakeling scott@diskfish.org

**Comment by spanezz** [comment]
On Sat, Feb 21, 2015 at 04:19:33PM -0800, Scott Wakeling wrote:

> > Would you like to take it over as the lead developer?
> > Thanks, I'll take it over. There's some more I'd like to add..

I tried to transfer the repository to you but it says that a repository
with the same name already exists. If you want you can delete your fork
of seat-inspect and I'll transfer mine to you.

Enrico

## 

GPG key: 4096R/E7AD5568 2009-05-08 Enrico Zini enrico@enricozini.org

**Comment by scottwakeling** [comment]
> I tried to transfer the repository to you but it says that a
> repository with the same name already exists. If you want you can
> delete your fork of seat-inspect and I'll transfer mine to you.

Ok, I've deleted the fork.

I'll hack on it some more and deal with any pull requests or issues
that come in.

-scott

## 

4096R/B4CCF23A 2014-11-20 Scott James Wakeling scott@diskfish.org

**Comment by spanezz** [comment]
On Wed, Feb 25, 2015 at 01:37:24PM -0800, Scott Wakeling wrote:

> > I tried to transfer the repository to you but it says that a
> > repository with the same name already exists. If you want you can
> > delete your fork of seat-inspect and I'll transfer mine to you.
> 
> Ok, I've deleted the fork.
> 
> I'll hack on it some more and deal with any pull requests or issues
> that come in.

That's great! I've started the transfer.

Enrico

## 

GPG key: 4096R/E7AD5568 2009-05-08 Enrico Zini enrico@enricozini.org

**Pull request merged**
